#!/usr/bin/env zsh

# install macos command line tools so we can install gcc used by yarn
xcode-select --install

# brew it up! install all the things; tapping where necessary 
brew update
brew tap aws/tap
brew install aws-cdk awscli aws-sam-cli gcc openjdk@8 node@12 python remotemobprogramming/brew/mob slack yarn 


# install IDEs (JetBrains products to start)
brew install --cask  intellij-idea webstorm postman

# OK, now let's update path: first in line python, then node
echo 'export PATH="/usr/local/opt/node@12/bin:$PATH"' >> ~/.zprofile
echo "export SAM=`which python3`" >> ~/.zprofile
echo "export PATH=$SAM/bin:$PATH" >> ~/.bash_profile

# Lastly, set up AWS creds for A-account
curl https://repo.forge.lmig.com/content/repositories/ets-releases/com/lmig/ets/public-cloud/aws-saml-api-keys/2.4-55/aws-saml-api-keys-2.4-55.zip --output aws-saml-api-keys-2.4-55.zip


unzip aws-saml-api-keys-2.4-55.zip
rm aws-saml-api-keys-2.4-55.zip
open apikeyretriever_darwin_amd64
