#!/usr/bin/env bash

usage() {
  echo "Usage: monitor-rate <env> <app>, where <env> is the environment whose containers you want to monitor and <app> is the application. (e.g: rate, persist, etc.)."
  exit 1;
}

#display usage info if no args passed
[[ $# -eq 0 ]] && usage 

DOCKER_CLI_HOME=$( [ "$1"=="production" ] && echo "$DOCKER_CLI_PROD" || echo "$DOCKER_CLI_NON_PROD")
cd ~/non_prod_docker_cli
eval $(<env.sh)
docker container ls | grep "slice-rent-simp-honeycomb-$1_$2*" | awk -F '[[:space:]][[:space:]]+'  '{split($0,a); print a[1] "    " a[2] "     " a[5]}'

#docker container ls | grep "slice-rent-simp-honeycomb-develop_rate-v1" | awk -F '[[:space:]][[:space:]]+'  '{split($0,a); print a[1] "    " a[2] "     " a[5]}'
